// Generated by https://quicktype.io

export interface RecipesResponse {
    results:      Recipe[];
    offset:       number;
    number:       number;
    totalResults: number;
}

export interface Recipe {
    id:        number;
    title:     string;
    image:     string;
    imageType: ImageType;
}

export enum ImageType {
    Jpg = "jpg",
}
